/**
 * Error catalogue mirrored from docs/ERROR-CODES.md.
 * `message` is the English default; the portal shows a translated
 * `errors.<code>` message when one exists (see useErrorHandler).
 */
export interface ErrorCodeDefinition {
  status: number
  message: string
}

export const ERROR_CODES = {
  'FRM-GEN-1001': { status: 400, message: 'Invalid request.' },
  'FRM-GEN-1002': { status: 422, message: 'Some fields are invalid.' },
  'FRM-GEN-1004': { status: 404, message: 'Not found.' },
  'FRM-GEN-1009': { status: 409, message: 'This item was changed by someone else. Reload and try again.' },
  'FRM-GEN-1029': { status: 429, message: 'Too many requests. Please slow down.' },
  'FRM-GEN-5000': { status: 500, message: 'Something went wrong. Our team has been notified.' },
  'FRM-GEN-5003': { status: 503, message: 'Service temporarily unavailable.' },
  'FRM-SEC-1001': { status: 400, message: 'Secure channel required.' },
  'FRM-SEC-1002': { status: 400, message: 'Request expired.' },
  'FRM-SEC-1003': { status: 400, message: 'Duplicate request rejected.' },
  'FRM-SEC-1004': { status: 401, message: 'Secure session expired.' },
  'FRM-SEC-1005': { status: 400, message: 'Request integrity check failed.' },
  'FRM-SEC-1006': { status: 403, message: 'Security token expired. Refresh the page.' },
  'FRM-SEC-1007': { status: 403, message: 'Request blocked.' },
  'FRM-AUTH-1001': { status: 401, message: 'Session expired.' },
  'FRM-AUTH-1002': { status: 401, message: 'Invalid email or password.' },
  'FRM-AUTH-1003': { status: 401, message: 'Invalid or expired code.' },
  'FRM-AUTH-1004': { status: 429, message: 'Too many attempts. Try again later.' },
  'FRM-AUTH-1005': { status: 403, message: 'Account disabled. Contact your administrator.' },
  'FRM-AUTH-1006': { status: 403, message: 'Multi-factor authentication required.' },
  'FRM-AUTH-1007': { status: 400, message: 'Password does not meet the policy.' },
  'FRM-AUTH-1008': { status: 400, message: 'This sign-in method is not enabled for this workspace.' },
  'FRM-AUTH-1010': { status: 401, message: 'Invalid token.' },
  'FRM-AUTH-1011': { status: 401, message: 'Session revoked.' },
  'FRM-AUTH-1012': { status: 401, message: 'Session ended for security reasons.' },
  'FRM-AUTH-1013': { status: 422, message: 'That password is not right.' },
  'FRM-AUTH-1014': { status: 403, message: "This email address can't sign in to this workspace." },
  'FRM-AUTH-1015': { status: 403, message: 'Your password has expired. Set a new one.' },
  'FRM-AUTH-1016': { status: 403, message: "Sign-in isn't allowed from this network." },
  'FRM-AUTH-1017': { status: 409, message: 'This change would lock you out.' },
  'FRM-AUTH-1018': { status: 422, message: 'You used this password recently. Choose another one.' },
  'FRM-PERM-1001': { status: 403, message: "You don't have access to this." },
  'FRM-TEN-1001': { status: 404, message: 'Workspace not found.' },
  'FRM-TEN-1002': { status: 403, message: 'Workspace suspended.' },
  'FRM-TEN-1003': { status: 403, message: 'Access denied for this workspace.' },
  'FRM-TEN-1004': { status: 409, message: 'Subdomain not available.' },
  'FRM-FORM-1001': { status: 404, message: 'Form not found or not published.' },
  'FRM-FORM-1002': { status: 400, message: 'Form is closed.' },
  'FRM-FORM-1003': { status: 400, message: 'Form has reached its response limit.' },
  'FRM-FORM-1004': { status: 422, message: 'Form cannot be published: fix the listed issues.' },
  'FRM-FORM-1005': { status: 403, message: 'Password required.' },
  'FRM-FORM-1006': { status: 409, message: 'Slug already in use.' },
  'FRM-FORM-1007': { status: 409, message: "This isn't possible while the form is in its current state." },
  'FRM-FORM-1008': { status: 409, message: 'A folder with this name already exists.' },
  'FRM-FORM-1009': { status: 409, message: 'A list with this name already exists.' },
  'FRM-FORM-1010': { status: 409, message: 'A theme with this name already exists.' },
  'FRM-FORM-1011': {
    status: 403,
    message: 'System templates can’t be changed. Duplicate it to make your own.',
  },
  'FRM-FORM-1012': { status: 409, message: 'A template with this name already exists.' },
  'FRM-FORM-1013': {
    status: 409,
    message: 'This folder still has forms. Move them to another folder first.',
  },
  'FRM-FORM-1014': { status: 403, message: 'System themes can’t be changed. Duplicate it to make your own.' },
  'FRM-FORM-1015': { status: 410, message: 'This form has expired.' },
  'FRM-FORM-1016': { status: 403, message: 'This form isn’t open yet.' },
  'FRM-FORM-1017': { status: 403, message: 'That password isn’t right.' },
  'FRM-FORM-1018': { status: 403, message: 'This invitation link isn’t valid any more.' },
  'FRM-FORM-1019': { status: 403, message: 'Your sign-in for this form has expired. Sign in again.' },
  'FRM-FORM-1020': { status: 422, message: 'Two options share the same value. Each value must be different.' },
  'FRM-FORM-1021': { status: 422, message: 'An option has no option above it. Choose where it belongs.' },
  'FRM-FORM-1022': { status: 422, message: 'This list has more options than it can hold: 20,000, or 200,000 when it is large.' },
  'FRM-RESP-1001': { status: 422, message: 'Submission is invalid.' },
  'FRM-RESP-1002': { status: 400, message: 'Verification failed.' },
  'FRM-RESP-1003': { status: 409, message: 'This form was already submitted from this session.' },
  'FRM-RESP-1004': { status: 409, message: 'This form was already submitted from this browser.' },
  'FRM-RESP-1005': { status: 409, message: 'A response with exactly these answers was already submitted.' },
  'FRM-RESP-1006': { status: 409, message: 'A response from this person was already submitted.' },
  'FRM-RESP-1007': {
    status: 409,
    message: 'This looks like a response that was already submitted. Confirm this is a different person.',
  },
  'FRM-RESP-1008': { status: 403, message: 'Verify your email to submit this form.' },
  'FRM-RESP-1009': {
    status: 403,
    message: 'We could not confirm this response was sent by a person. Please try again.',
  },
  'FRM-FILE-1001': { status: 400, message: 'File type not allowed.' },
  'FRM-FILE-1002': { status: 413, message: 'File too large.' },
  'FRM-FILE-1003': { status: 400, message: 'File failed security scan.' },
  'FRM-EXP-1001': { status: 404, message: 'Export not found or expired.' },
  'FRM-DEST-1001': { status: 400, message: 'Could not connect to destination database.' },
  'FRM-DEST-1002': { status: 400, message: 'The database did not accept the user name or password.' },
  'FRM-DEST-1003': {
    status: 400,
    message: 'The encrypted connection could not be set up (certificate or TLS settings).',
  },
  'FRM-DEST-1004': { status: 400, message: 'Could not open the SSH tunnel.' },
  'FRM-DEST-1005': {
    status: 400,
    message: 'The database or schema was not found, or this account may not use it.',
  },
  'FRM-DEST-1006': { status: 400, message: 'Some permissions this connection needs are missing.' },
  'FRM-DEST-1007': { status: 409, message: 'A connection with this name already exists.' },
  'FRM-DEST-1008': { status: 404, message: 'This connection test is no longer available. Run it again.' },
  'FRM-DEST-1009': { status: 409, message: 'This connection is disabled. Enable it first.' },
  'FRM-DEST-1010': { status: 409, message: 'Forms still send their responses to this connection.' },
  'FRM-DEST-1011': { status: 400, message: 'The database took too long to answer.' },
  'FRM-DEST-1013': {
    status: 403,
    message: 'Storing responses in a table of yours needs Full access on this connection.',
  },
  'FRM-DEST-1014': { status: 409, message: 'A table with this name already exists.' },
  'FRM-DEST-1015': { status: 409, message: 'This form already stores its responses in a database.' },
  'FRM-DEST-1016': { status: 422, message: "The form and the table don't match yet." },
  'FRM-DEST-1017': {
    status: 409,
    message: 'Earlier responses are already being sent. Wait until that finishes.',
  },
  'FRM-DEST-1018': { status: 409, message: 'A row with this key already exists.' },
  'FRM-DEST-1019': { status: 403, message: "This table's rows can't be changed here." },
  'FRM-DEST-1022': { status: 409, message: 'That name is already used. Choose another one.' },
  'FRM-DEST-1023': { status: 409, message: 'This statement changes data. Confirm to run it.' },
  'FRM-DEST-1024': { status: 403, message: 'This connection is read only here: only reading statements run.' },
  'FRM-DEST-1025': { status: 400, message: "The database couldn't run this statement." },
  'FRM-DEST-1026': { status: 400, message: 'Run one statement at a time: select it, or put the cursor in it.' },
  'FRM-DEST-1027': { status: 403, message: 'Only the person who saved this query can change it.' },
  'FRM-DEST-1012': { status: 400, message: "This account can't create or use the response tables." },
  'FRM-API-1001': { status: 409, message: 'This endpoint name is already used in your organisation.' },
  'FRM-API-1002': { status: 422, message: 'Publish the form before it can be an endpoint.' },
  'FRM-API-1003': { status: 409, message: 'A service with this name already exists.' },
  'FRM-API-1004': { status: 409, message: 'This token was revoked and can no longer be changed.' },
  'FRM-API-1005': { status: 409, message: 'Revoke the token before deleting it.' },
  'FRM-API-1006': { status: 404, message: 'There is no endpoint at this address.' },
  'FRM-API-1007': { status: 503, message: 'This endpoint is switched off.' },
  'FRM-API-1008': { status: 405, message: 'This endpoint does not answer this method.' },
  'FRM-API-1009': { status: 403, message: 'This token may not call this endpoint or method.' },
  'FRM-API-1010': { status: 401, message: 'Send a valid token as Authorization: Bearer <token>.' },
  'FRM-API-1011': { status: 400, message: 'The Formalie-Key header is missing or not valid. Send a new unique id (a UUID) with every POST.' },
  'FRM-API-1012': { status: 401, message: 'The request signature is missing, too old or wrong.' },
  'FRM-API-1013': { status: 404, message: 'There is no record with this id.' },
  'FRM-API-1014': { status: 422, message: 'Some fields can not be sent to this endpoint.' },
  'FRM-API-1015': { status: 403, message: 'This caller is not allowed by the access rules.' },
  'FRM-API-1017': { status: 415, message: 'Send the body as JSON with Content-Type: application/json.' },
  'FRM-API-1018': { status: 413, message: 'The body is too large (1 MB at most; send files through the upload step).' },
  'FRM-API-1020': { status: 409, message: 'This Formalie-Key was already used for a different request. Send a new key for every new record.' },
  'FRM-API-1019': { status: 422, message: 'This form is not open to the API service. Turn the API on in its Share settings.' },
  'FRM-API-1016': { status: 409, message: 'This secret can not be shown: it was made before secrets could be viewed again. Rotate it for a new one.' },
  'FRM-USER-1001': { status: 410, message: 'This invitation has expired. Ask the person who invited you for a new one.' },
  'FRM-USER-1002': { status: 404, message: 'This invitation is no longer valid. It may have been used or withdrawn.' },
  'FRM-USER-1003': { status: 409, message: 'A workspace needs at least one owner. Make someone else an owner first.' },
  'FRM-USER-1004': { status: 422, message: "A person can't report to themselves or to someone who reports to them." },
  'FRM-USER-1005': { status: 409, message: "You can't do this to your own account." },
  'FRM-USER-1006': { status: 403, message: 'Only owners can make someone an owner or change an owner.' },
  'FRM-USER-1007': { status: 409, message: "The built-in roles can't be deleted, and Owner can't be changed." },
  'FRM-USER-1008': { status: 409, message: 'People hold this role. Give them another role first.' },
  'FRM-USER-1009': { status: 422, message: 'This role does not exist any more. Choose another one.' },
  'FRM-USER-1010': { status: 403, message: "Your account is waiting for an admin's approval. You'll get an email when you can sign in." },
  'FRM-USER-1011': { status: 409, message: 'This email address already has an account here. Sign in instead.' },
  'FRM-USER-1012': { status: 422, message: "This sign-up link only accepts the organisation's email addresses." },
  'FRM-AI-1001': { status: 403, message: 'The AI assistant is switched off for this workspace.' },
  'FRM-AI-1002': { status: 429, message: "This month's AI allowance has been used. It renews at the start of next month." },
  'FRM-AI-1003': { status: 403, message: "The AI assistant isn't allowed to read this part of the workspace. An admin can change it in AI settings." },
  'FRM-ORG-1001': { status: 409, message: 'An entry with this name already exists.' },
  'FRM-ORG-1002': { status: 409, message: 'Forms still use it. Archive it, or merge it into another one.' },
  'FRM-PLAN-1001': { status: 402, message: 'Your plan limit has been reached. Upgrade to continue.' },
  'FRM-PLAN-1002': { status: 402, message: 'This feature is not included in your plan.' },
} as const satisfies Record<string, ErrorCodeDefinition>

export type ErrorCode = keyof typeof ERROR_CODES
