import { describe, expect, it } from 'vitest'
import { changeStatements, checkName, createTableStatements, kindsFor, specOfType, typeChangeRisky, typeFor, type ColumnSpec } from '#shared/utils/datasources/ddl'

const columns: ColumnSpec[] = [
  { name: 'id', kind: 'big_integer', nullable: false, primary: true, auto: true },
  { name: 'name', kind: 'text', length: 200, nullable: false, default: 'none' },
  { name: 'active', kind: 'boolean', nullable: true, default: 'true' },
]

describe('types per engine', () => {
  it('maps kinds to each engine', () => {
    expect(typeFor('postgresql', { kind: 'datetime' })).toBe('TIMESTAMPTZ')
    expect(typeFor('sqlserver', { kind: 'text', length: 50 })).toBe('NVARCHAR(50)')
    expect(typeFor('oracle', { kind: 'decimal', length: 10, scale: 3 })).toBe('NUMBER(10,3)')
    expect(typeFor('mysql', { kind: 'boolean' })).toBe('TINYINT(1)')
    expect(kindsFor('oracle')).not.toContain('time')
  })

  it('reads kinds back from types', () => {
    expect(specOfType('VARCHAR(320)')).toEqual({ kind: 'text', length: 320 })
    expect(specOfType('NUMERIC(12,2)')).toEqual({ kind: 'decimal', length: 12, scale: 2 })
    expect(specOfType('NUMBER(19)').kind).toBe('big_integer')
    expect(specOfType('TEXT').kind).toBe('long_text')
  })
})

describe('names', () => {
  it('checks table, column and index names', () => {
    expect(checkName('postgresql', '', 'table')).toBe('required')
    expect(checkName('postgresql', '1abc', 'column')).toBe('chars')
    expect(checkName('postgresql', 'a'.repeat(64), 'table')).toBe('long')
    expect(checkName('mysql', 'formalie_things', 'table')).toBe('prefix')
    expect(checkName('mysql', 'formalie_things', 'column')).toBeNull()
  })
})

describe('CREATE TABLE', () => {
  it('writes identity, defaults and the key per engine', () => {
    const pg = createTableStatements('postgresql', 'public', 'contacts', columns)[0]!
    expect(pg).toContain('"id" BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL')
    expect(pg).toContain(`"name" VARCHAR(200) DEFAULT 'none' NOT NULL`)
    expect(pg).toContain('"active" BOOLEAN DEFAULT TRUE')
    expect(pg).toContain('CONSTRAINT "contacts_pk" PRIMARY KEY ("id")')
    const my = createTableStatements('mysql', 'app', 'contacts', columns)[0]!
    expect(my).toContain('`id` BIGINT NOT NULL AUTO_INCREMENT')
    const ss = createTableStatements('sqlserver', 'dbo', 'contacts', columns)[0]!
    expect(ss).toContain('[id] BIGINT IDENTITY(1,1) NOT NULL')
    expect(ss).toContain(`[name] NVARCHAR(200) CONSTRAINT [DF_contacts_name] DEFAULT N'none' NOT NULL`)
  })
})

describe('changes', () => {
  const current = { name: 'phone', type: 'VARCHAR(200)', nullable: true, default: null, primary: false }
  const to: ColumnSpec = { name: 'mobile', kind: 'text', length: 40, nullable: false }

  it('renames and changes a column per engine', () => {
    expect(changeStatements('postgresql', 'public', 'clients', { op: 'alter_column', column: 'phone', to }, current)).toEqual([
      'ALTER TABLE "public"."clients" RENAME COLUMN "phone" TO "mobile";',
      'ALTER TABLE "public"."clients" ALTER COLUMN "mobile" TYPE VARCHAR(40) USING "mobile"::VARCHAR(40);',
      'ALTER TABLE "public"."clients" ALTER COLUMN "mobile" SET NOT NULL;',
    ])
    expect(changeStatements('sqlserver', 'dbo', 'clients', { op: 'alter_column', column: 'phone', to }, current)[0]).toBe("EXEC sp_rename N'dbo.clients.phone', N'mobile', N'COLUMN';")
    expect(changeStatements('mysql', 'app', 'clients', { op: 'alter_column', column: 'phone', to }, current)[1]).toBe('ALTER TABLE `app`.`clients` MODIFY COLUMN `mobile` VARCHAR(40) NOT NULL;')
    expect(changeStatements('oracle', 'APP', 'CLIENTS', { op: 'alter_column', column: 'phone', to }, current)[1]).toBe('ALTER TABLE "APP"."CLIENTS" MODIFY ("mobile" VARCHAR2(40) NOT NULL);')
  })

  it('writes nothing when nothing changed', () => {
    expect(changeStatements('postgresql', 'public', 'clients', { op: 'alter_column', column: 'phone', to: { name: 'phone', kind: 'text', length: 200, nullable: true } }, current)).toEqual([])
  })

  it('adds, renames, indexes, empties and deletes per engine', () => {
    expect(changeStatements('oracle', 'APP', 'T', { op: 'add_column', column: { name: 'NOTE', kind: 'long_text', nullable: true } })).toEqual(['ALTER TABLE "APP"."T" ADD ("NOTE" CLOB);'])
    expect(changeStatements('sqlserver', 'dbo', 't', { op: 'add_column', column: { name: 'note', kind: 'text', nullable: true } })).toEqual(['ALTER TABLE [dbo].[t] ADD [note] NVARCHAR(255);'])
    expect(changeStatements('mariadb', 'app', 't', { op: 'rename_table', name: 'u' })).toEqual(['RENAME TABLE `app`.`t` TO `app`.`u`;'])
    expect(changeStatements('sqlserver', 'dbo', 't', { op: 'rename_table', name: 'u' })).toEqual(["EXEC sp_rename N'dbo.t', N'u';"])
    expect(changeStatements('postgresql', 'public', 't', { op: 'add_index', name: 't_a_uq', columns: ['a', 'b'], unique: true })).toEqual(['CREATE UNIQUE INDEX "t_a_uq" ON "public"."t" ("a", "b");'])
    expect(changeStatements('postgresql', 'public', 't', { op: 'drop_index', name: 'i' })).toEqual(['DROP INDEX "public"."i";'])
    expect(changeStatements('mysql', 'app', 't', { op: 'drop_index', name: 'i' })).toEqual(['DROP INDEX `i` ON `app`.`t`;'])
    expect(changeStatements('postgresql', 'public', 't', { op: 'truncate' })).toEqual(['TRUNCATE TABLE "public"."t";'])
    expect(changeStatements('postgresql', 'public', 't', { op: 'drop_table' })).toEqual(['DROP TABLE "public"."t";'])
  })

  it('flags changes that may lose data', () => {
    expect(typeChangeRisky('VARCHAR(200)', { kind: 'text', length: 40 })).toBe(true)
    expect(typeChangeRisky('VARCHAR(40)', { kind: 'text', length: 200 })).toBe(false)
    expect(typeChangeRisky('INTEGER', { kind: 'big_integer' })).toBe(false)
    expect(typeChangeRisky('TEXT', { kind: 'integer' })).toBe(true)
  })
})
