/** Business & Customer templates (F9 milestone 1). */
import { opts, page, q, row, rule, scored, type TemplateDef } from '../kit'


export const BUSINESS_TEMPLATES: TemplateDef[] = [
  {
    key: 'customer_feedback',
    category: 'business',
    icon: 'i-lucide-message-square-heart',
    minutes: 3,
    name: 'Customer Feedback',
    description: 'Hear what customers think of your service — with a follow-up when someone is unhappy.',
    tags: ['feedback', 'nps', 'service'],
    pages: [
      page('Your feedback', [
        q('scale', 'How likely are you to recommend us to a friend or colleague?', {
          key: 'recommend',
          required: true,
          props: { min: 0, max: 10, min_label: 'Not likely', max_label: 'Very likely' },
        }),
        q('long_text', 'We are sorry to hear that. What disappointed you?', { key: 'disappointed' }),
        q('rating', 'How satisfied are you overall?', { key: 'overall', required: true }),
        q('radio', 'What did you mainly use?', { options: opts('Website', 'Mobile app', 'Customer support', 'In person', 'Other') }),
        q('matrix', 'How would you rate us on…', {
          options: opts('Poor', 'Fair', 'Good', 'Excellent'),
          props: { rows: ['Quality', 'Speed', 'Value for money', 'Friendliness'] },
        }),
        q('long_text', 'What could we do better?'),
        row(q('short_text', 'Name'), q('email', 'Email')),
        q('toggle', 'You may contact me about my feedback'),
      ]),
    ],
    logic: [rule([['recommend', 'lte', 6]], [['show', 'disappointed']])],
    thankYou: { title: 'Thank you for your feedback!', message: 'Every answer is read by our team and helps us improve.' },
  },
  {
    key: 'csat_nps',
    category: 'business',
    icon: 'i-lucide-smile-plus',
    minutes: 2,
    name: 'Customer Satisfaction (CSAT / NPS) Survey',
    description: 'Measure satisfaction (CSAT), effort and loyalty (NPS) — each answer is grouped as promoter, passive or detractor.',
    tags: ['csat', 'nps', 'ces', 'survey'],
    design: { colors: { primary: '#7c3aed' }, header: { band_bg: '#7c3aed', band_to: '#2563eb' } },
    pages: [
      page('Your experience', [
        q('rating', 'Overall, how satisfied are you with our service?', { key: 'csat', required: true }),
        q('radio', 'How easy was it to get what you needed?', {
          key: 'effort',
          options: scored(['Very difficult', 1], ['Difficult', 2], ['Neither', 3], ['Easy', 4], ['Very easy', 5]),
        }),
        q('scale', 'How likely are you to recommend us?', {
          key: 'nps',
          required: true,
          props: { min: 0, max: 10, min_label: 'Not at all likely', max_label: 'Extremely likely' },
        }),
        q('calculated', 'Loyalty group', {
          key: 'nps_group',
          formula: 'if({nps} >= 9, "Promoter", if({nps} >= 7, "Passive", "Detractor"))',
          props: { internal: true },
          help: 'Promoter 9–10 · Passive 7–8 · Detractor 0–6 — for your team, not shown to respondents.',
        }),
        q('long_text', 'What could we do to win back your trust?', { key: 'win_back' }),
        q('checkbox', 'What did we do well?', { options: opts('Quick response', 'Friendly staff', 'Solved my problem', 'Good value', 'Easy to use') }),
        q('long_text', 'Anything else you would like to tell us?'),
      ]),
    ],
    logic: [rule([['nps', 'lte', 6]], [['show', 'win_back']])],
  },
  {
    key: 'product_review',
    category: 'business',
    icon: 'i-lucide-star',
    minutes: 4,
    name: 'Product Review',
    description: 'Collect detailed product reviews with star ratings, an average score, photos and publishing consent.',
    tags: ['review', 'rating', 'product'],
    design: { colors: { primary: '#d97706' }, header: { band_bg: '#b45309', band_to: '#f59e0b' } },
    pages: [
      page('Your review', [
        q('short_text', 'Which product are you reviewing?', { required: true }),
        q('rating', 'Overall rating', { key: 'overall', required: true }),
        row(q('rating', 'Quality', { key: 'quality' }), q('rating', 'Value for money', { key: 'value' }), q('rating', 'Ease of use', { key: 'ease' })),
        q('calculated', 'Average rating', { key: 'average', formula: 'round(avg({overall}, {quality}, {value}, {ease}), 1)' }),
        q('radio', 'Would you recommend this product?', { options: opts('Yes', 'No') }),
        q('short_text', 'Review title', { required: true, placeholder: 'Sum it up in a few words' }),
        q('long_text', 'Your review', { required: true, validation: { min_length: 20, max_length: 2000 } }),
        q('image_upload', 'Photos (optional)', { props: { max_files: 4 } }),
        row(q('short_text', 'Name shown with your review'), q('email', 'Email (not published)')),
        q('consent', 'Publishing', { required: true, props: { text: 'I agree that my review, rating and display name may be published.' } }),
      ]),
    ],
  },
  {
    key: 'contact_lead',
    category: 'business',
    icon: 'i-lucide-contact',
    minutes: 2,
    name: 'Contact / Inquiry Form',
    description: 'A simple, friendly contact form that routes each inquiry by topic.',
    tags: ['contact', 'inquiry', 'website'],
    design: { colors: { primary: '#2563eb' }, header: { band_bg: '#1d4ed8', band_to: '#0ea5e9' } },
    pages: [
      page('Contact us', [
        row(q('short_text', 'Name', { required: true }), q('email', 'Email', { required: true })),
        row(q('phone', 'Phone'), q('short_text', 'Company')),
        q('dropdown', 'What is it about?', { key: 'topic', required: true, options: opts('Sales', 'Support', 'Partnership', 'Press', 'Other') }),
        q('short_text', 'Order or ticket number', { key: 'reference' }),
        q('long_text', 'Message', { required: true }),
        q('radio', 'How should we reply?', { options: opts('Email', 'Phone') }),
        q('hidden', 'Source', { props: { param: 'utm_source' } }),
      ]),
    ],
    logic: [rule([['topic', 'eq', 'support']], [['show', 'reference']])],
  },
  {
    key: 'quote_request',
    category: 'business',
    icon: 'i-lucide-calculator',
    minutes: 4,
    name: 'Quote / Estimate Request',
    description: 'Let customers build a request and see an indicative estimate from package, add-ons and quantity.',
    tags: ['quote', 'estimate', 'pricing'],
    design: { colors: { primary: '#0f766e' }, header: { band_bg: '#0f766e', band_to: '#22c55e' } },
    pages: [
      page('Your request', [
        row(q('short_text', 'Name', { required: true }), q('email', 'Email', { required: true })),
        row(q('phone', 'Phone'), q('short_text', 'Company')),
        q('radio', 'Package', { key: 'package', required: true, options: scored(['Basic', 500], ['Standard', 1200], ['Premium', 2500]) }),
        q('checkbox', 'Add-ons', { key: 'addons', options: scored(['Installation', 150], ['Training', 300], ['Extended support (12 months)', 400]) }),
        q('number', 'Quantity', { key: 'quantity', required: true, default: 1, validation: { min: 1, max: 1000 } }),
        q('calculated', 'Indicative estimate', {
          key: 'estimate',
          formula: '({package} + if(count({addons}) > 0, {addons}, 0)) * {quantity}',
          help: 'Package plus add-ons, times quantity. The final quote may differ.',
        }),
        q('date', 'When do you need it?'),
        q('long_text', 'Tell us more about what you need'),
        q('file_upload', 'Attachments (plans, specifications)', { props: { max_files: 5 } }),
      ]),
    ],
  },
  {
    key: 'order_form',
    category: 'business',
    icon: 'i-lucide-shopping-cart',
    minutes: 5,
    name: 'Order Form',
    description: 'Take orders with up to three product lines, delivery choice and a running total.',
    tags: ['order', 'purchase', 'total'],
    design: { colors: { primary: '#16a34a' }, header: { band_bg: '#15803d', band_to: '#65a30d' } },
    pages: [
      page('Your order', [
        q('section', 'Products', { props: { description: 'Choose up to three products.' } }),
        ...[1, 2, 3].map(n =>
          row(
            q('dropdown', `Product ${n}`, {
              key: `product_${n}`,
              required: n === 1,
              width: 6,
              options: scored(['Starter kit — 25.00', 25], ['Standard pack — 45.00', 45], ['Professional set — 90.00', 90], ['Refill bundle — 15.00', 15]),
            }),
            q('number', 'Qty', { key: `qty_${n}`, width: 2, default: n === 1 ? 1 : undefined, validation: { min: 0, max: 999 } }),
            q('calculated', 'Line total', { key: `line_${n}`, width: 4, formula: `{product_${n}} * {qty_${n}}` }),
          ),
        ),
        q('radio', 'Delivery', { key: 'delivery', required: true, options: scored(['Standard (free)', 0], ['Express — 15.00', 15], ['Collect in store', 0]) }),
        row(q('calculated', 'Subtotal', { key: 'subtotal', formula: 'sum({line_1}, {line_2}, {line_3})' }), q('calculated', 'Total', { key: 'total', formula: '{subtotal} + {delivery}' })),
      ]),
      page('Delivery details', [
        row(q('short_text', 'Name', { required: true }), q('email', 'Email', { required: true })),
        q('phone', 'Phone'),
        q('address', 'Delivery address', { required: true }),
        q('date', 'Preferred delivery date'),
        q('long_text', 'Notes for the order'),
        q('consent', 'Terms', { required: true, props: { text: 'I agree to the terms of sale.' } }),
      ]),
    ],
  },
  {
    key: 'complaint_dispute',
    category: 'business',
    icon: 'i-lucide-message-square-warning',
    minutes: 5,
    name: 'Complaint / Dispute Form',
    description: 'Record complaints and disputes with evidence, the outcome wanted and earlier contact.',
    tags: ['complaint', 'dispute', 'resolution'],
    design: { colors: { primary: '#be123c' }, header: { band_bg: '#9f1239', band_to: '#e11d48' } },
    pages: [
      page('About you', [
        q('full_name', 'Your name', { required: true }),
        row(q('email', 'Email', { required: true }), q('phone', 'Phone')),
        q('short_text', 'Order, account or reference number'),
      ]),
      page('Your complaint', [
        row(q('date', 'When did it happen?', { required: true }), q('dropdown', 'What is it about?', { required: true, options: opts('Product', 'Service', 'Billing', 'Delivery', 'Staff', 'Other') })),
        q('radio', 'How serious is this for you?', { options: opts('Minor', 'Significant', 'Serious') }),
        q('long_text', 'What happened?', { required: true, validation: { min_length: 20 } }),
        q('long_text', 'What outcome would you like?', { required: true }),
        q('file_upload', 'Evidence (photos, receipts, letters)', { props: { max_files: 5 } }),
        q('toggle', 'Have you contacted us about this before?', { key: 'contacted_before' }),
        q('short_text', 'Earlier reference number', { key: 'earlier_reference' }),
        q('consent', 'Declaration', { required: true, props: { text: 'The information I have given is true to the best of my knowledge.' } }),
      ]),
    ],
    logic: [rule([['contacted_before', 'true']], [['show', 'earlier_reference']])],
  },
  {
    key: 'service_request',
    category: 'business',
    icon: 'i-lucide-wrench',
    minutes: 3,
    name: 'Service Request',
    description: 'Book a service visit with priority, preferred time and photos of the problem.',
    tags: ['service', 'request', 'booking'],
    design: { colors: { primary: '#0369a1' }, header: { band_bg: '#075985', band_to: '#0891b2' } },
    pages: [
      page('Service request', [
        row(q('short_text', 'Name', { required: true }), q('email', 'Email', { required: true })),
        q('phone', 'Phone', { key: 'phone' }),
        q('address', 'Service address', { required: true }),
        q('dropdown', 'Type of service', { required: true, options: opts('Installation', 'Repair', 'Maintenance', 'Inspection', 'Other') }),
        q('radio', 'Priority', { key: 'priority', required: true, options: opts('Low', 'Normal', 'Urgent') }),
        row(q('date', 'Preferred date'), q('radio', 'Preferred time', { options: opts('Morning', 'Afternoon', 'Evening') })),
        q('long_text', 'Describe the problem', { required: true }),
        q('image_upload', 'Photos', { props: { max_files: 4 } }),
      ]),
    ],
    logic: [rule([['priority', 'eq', 'urgent']], [['require', 'phone']])],
  },
  {
    key: 'lead_capture_newsletter',
    category: 'business',
    icon: 'i-lucide-mail-plus',
    minutes: 1,
    name: 'Lead Capture / Newsletter Signup',
    description: 'Grow your list with consent, interests and campaign tracking built in.',
    tags: ['newsletter', 'lead', 'marketing'],
    design: { colors: { primary: '#c026d3' }, header: { band_bg: '#a21caf', band_to: '#f43f5e' } },
    pages: [
      page('Stay in touch', [
        row(q('short_text', 'First name', { required: true }), q('short_text', 'Last name')),
        q('email', 'Email', { required: true }),
        q('country', 'Country'),
        q('multi_select', 'What are you interested in?', { options: opts('Product updates', 'Events', 'Offers', 'Industry news', 'Tips and guides') }),
        q('radio', 'How often would you like to hear from us?', { options: opts('Weekly', 'Monthly') }),
        q('consent', 'Email consent', { required: true, props: { text: 'I would like to receive emails. I can unsubscribe at any time.' } }),
        row(q('hidden', 'Campaign source', { props: { param: 'utm_source' } }), q('hidden', 'Campaign', { props: { param: 'utm_campaign' } })),
      ]),
    ],
    thankYou: { title: "You're on the list!", message: 'Check your inbox to confirm your email address.' },
  },
  {
    key: 'return_refund',
    category: 'business',
    icon: 'i-lucide-undo-2',
    minutes: 4,
    name: 'Return / Refund Request',
    description: 'Handle returns with the reason, photos, the outcome wanted and the refund amount worked out.',
    tags: ['return', 'refund', 'exchange'],
    design: { colors: { primary: '#ea580c' }, header: { band_bg: '#c2410c', band_to: '#f97316' } },
    pages: [
      page('Your return', [
        row(q('short_text', 'Name', { required: true }), q('email', 'Email', { required: true })),
        row(q('short_text', 'Order number', { required: true }), q('date', 'Date of purchase')),
        q('short_text', 'Product', { required: true }),
        row(q('number', 'Quantity returned', { key: 'quantity', required: true, default: 1, validation: { min: 1 } }), q('currency', 'Price paid (each)', { key: 'unit_price', required: true })),
        q('calculated', 'Refund amount (before checks)', { key: 'refund_amount', formula: 'round({quantity} * {unit_price}, 2)' }),
        q('radio', 'Reason', { key: 'reason', required: true, options: opts('Damaged', 'Wrong item', 'Not as described', 'Changed my mind', 'Other') }),
        q('long_text', 'Tell us more', { key: 'details' }),
        q('image_upload', 'Photos of the item', { props: { max_files: 4 } }),
        q('radio', 'What would you like?', { key: 'resolution', required: true, options: opts('Refund', 'Exchange', 'Store credit') }),
        q('short_text', 'What would you like instead?', { key: 'exchange_for' }),
      ]),
    ],
    logic: [
      rule([['resolution', 'eq', 'exchange']], [['show', 'exchange_for'], ['require', 'exchange_for']]),
      rule([['reason', 'in', ['other', 'damaged', 'not_as_described']]], [['require', 'details']]),
    ],
  },
]

