/** Events & Bookings templates (F9 milestone 2). */
import { opts, page, q, row, rule, scored, type TemplateDef } from '../kit'

export const EVENTS_TEMPLATES: TemplateDef[] = [
  {
    key: 'event_registration',
    category: 'events',
    icon: 'i-lucide-calendar-check',
    minutes: 4,
    name: 'Event Registration',
    description: 'Register attendees with ticket type, quantity and a running total, sessions and access needs.',
    tags: ['event', 'registration', 'tickets'],
    pages: [
      page('Your details', [
        row(q('short_text', 'First name', { required: true }), q('short_text', 'Last name', { required: true })),
        row(q('email', 'Email', { required: true }), q('phone', 'Phone')),
        row(q('short_text', 'Organisation'), q('short_text', 'Job title')),
      ]),
      page('Your tickets', [
        q('radio', 'Ticket type', { key: 'ticket', required: true, options: scored(['Standard — 120.00', 120], ['VIP — 250.00', 250], ['Student — 60.00', 60]) }),
        row(
          q('number', 'Number of tickets', { key: 'tickets', required: true, default: 1, validation: { min: 1, max: 20 } }),
          q('calculated', 'Total', { key: 'total', formula: '{ticket} * {tickets}' }),
        ),
        q('checkbox', 'Sessions you would like to attend', { options: opts('Opening keynote', 'Workshop A', 'Workshop B', 'Panel discussion', 'Networking evening') }),
        q('dropdown', 'Dietary needs', { options: opts('None', 'Vegetarian', 'Vegan', 'Halal', 'Kosher', 'Gluten-free', 'Other') }),
        q('long_text', 'Accessibility needs'),
        q('consent', 'Terms', { required: true, props: { text: 'I agree to the event terms and the privacy notice.' } }),
      ]),
    ],
    thankYou: { title: "You're registered!", message: 'We have sent the details to your email. See you there.' },
  },
  {
    key: 'rsvp',
    category: 'events',
    icon: 'i-lucide-mail-check',
    minutes: 1,
    name: 'RSVP',
    description: 'Simple yes / no / maybe replies with party size and dietary needs only for those coming.',
    tags: ['rsvp', 'invitation'],
    design: { header: { band_bg: '#7c3aed' } },
    pages: [
      page('Will you join us?', [
        q('full_name', 'Your name', { required: true }),
        q('email', 'Email', { required: true }),
        q('radio', 'Will you attend?', { key: 'attending', required: true, options: opts('Yes', 'No', 'Maybe') }),
        q('number', 'How many people, including you?', { key: 'party_size', default: 1, validation: { min: 1, max: 10 } }),
        q('calculated', 'Confirmed guests', { key: 'guests', formula: 'if({attending} = "yes", {party_size}, 0)', props: { internal: true } }),
        q('multi_select', 'Dietary needs', { key: 'dietary', options: opts('Vegetarian', 'Vegan', 'Halal', 'Kosher', 'Gluten-free', 'Nut allergy') }),
        q('long_text', 'A message for the hosts'),
      ]),
    ],
    logic: [rule([['attending', 'in', ['yes', 'maybe']]], [['show', 'party_size'], ['show', 'dietary']])],
  },
  {
    key: 'appointment_booking',
    category: 'events',
    icon: 'i-lucide-calendar-clock',
    minutes: 2,
    name: 'Appointment Booking',
    description: 'Book a service on a preferred date and time, with a second choice and reminders.',
    tags: ['appointment', 'booking'],
    design: { header: { band_bg: '#0f766e' }, colors: { primary: '#0f766e' } },
    pages: [
      page('Book an appointment', [
        q('full_name', 'Name', { required: true }),
        row(q('email', 'Email', { required: true }), q('phone', 'Phone', { required: true })),
        q('dropdown', 'Service', { required: true, options: opts('Consultation', 'Follow-up', 'Assessment', 'Support session', 'Other') }),
        row(q('date', 'Preferred date', { required: true }), q('time', 'Preferred time', { required: true })),
        row(q('date', 'Second choice date'), q('time', 'Second choice time')),
        q('radio', 'Is this your first visit?', { options: opts('Yes', 'No') }),
        q('long_text', 'Anything we should know?'),
        q('toggle', 'Send me a reminder the day before', { default: true }),
      ]),
    ],
  },
  {
    key: 'venue_booking',
    category: 'events',
    icon: 'i-lucide-door-closed',
    minutes: 3,
    name: 'Venue / Room Reservation',
    description: 'Reserve a room by the hour with equipment add-ons and a cost worked out as you choose.',
    tags: ['venue', 'room', 'reservation'],
    design: { header: { band_bg: '#1d4ed8' }, colors: { primary: '#1d4ed8' } },
    pages: [
      page('Reservation', [
        row(q('full_name', 'Name', { required: true }), q('email', 'Email', { required: true })),
        q('short_text', 'Organisation'),
        q('radio', 'Room', { key: 'room', required: true, options: scored(['Meeting room — 40.00 / hour', 40], ['Board room — 75.00 / hour', 75], ['Event hall — 150.00 / hour', 150]) }),
        row(q('date', 'Date', { required: true }), q('time', 'Start time', { required: true }), q('number', 'Hours', { key: 'hours', required: true, default: 2, validation: { min: 1, max: 12 } })),
        q('number', 'Number of attendees', { validation: { min: 1, max: 1000 } }),
        q('checkbox', 'Equipment', { key: 'equipment', options: scored(['Projector — 20.00', 20], ['Video conferencing — 30.00', 30], ['Catering set-up — 50.00', 50]) }),
        row(
          q('calculated', 'Room cost', { key: 'room_cost', formula: '{room} * {hours}' }),
          q('calculated', 'Estimated total', { key: 'estimated_total', formula: '{room_cost} + if(count({equipment}) > 0, {equipment}, 0)' }),
        ),
        q('long_text', 'Notes'),
      ]),
    ],
  },
  {
    key: 'volunteer_signup',
    category: 'events',
    icon: 'i-lucide-hand-helping',
    minutes: 4,
    name: 'Volunteer Signup',
    description: 'Collect volunteers, their interests and availability — with guardian consent for under-18s.',
    tags: ['volunteer', 'availability'],
    design: { header: { band_bg: '#15803d' }, colors: { primary: '#15803d' } },
    pages: [
      page('About you', [
        q('full_name', 'Full name', { required: true }),
        row(q('email', 'Email', { required: true }), q('phone', 'Phone', { required: true })),
        q('radio', 'Age group', { key: 'age_group', required: true, options: opts('Under 18', '18–25', '26–40', '41–60', 'Over 60') }),
        q('full_name', 'Parent or guardian name', { key: 'guardian_name' }),
        q('consent', 'Guardian consent', { key: 'guardian_consent', props: { text: 'As parent or guardian, I agree to this person volunteering.' } }),
      ]),
      page('How you can help', [
        q('checkbox', 'Areas you are interested in', { required: true, options: opts('Welcome desk', 'Set-up and pack-down', 'Catering', 'Photography', 'First aid', 'Stewarding') }),
        q('checkbox', 'Days you are available', { options: opts('Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday') }),
        q('radio', 'Preferred time', { options: opts('Morning', 'Afternoon', 'Evening', 'Any time') }),
        q('long_text', 'Relevant experience'),
        row(q('short_text', 'Emergency contact'), q('phone', 'Emergency contact phone')),
      ]),
    ],
    logic: [rule([['age_group', 'eq', 'under_18']], [['show', 'guardian_name'], ['require', 'guardian_name'], ['show', 'guardian_consent'], ['require', 'guardian_consent']])],
  },
  {
    key: 'speaker_sponsor_application',
    category: 'events',
    icon: 'i-lucide-mic',
    minutes: 6,
    name: 'Speaker / Sponsor Application',
    description: 'One form for both: speakers propose a session, sponsors pick a package and add-ons with a total.',
    tags: ['speaker', 'sponsor', 'call for papers'],
    pages: [
      page('About you', [
        q('radio', 'Applying as', { key: 'role', required: true, options: opts('Speaker', 'Sponsor') }),
        q('full_name', 'Name', { required: true }),
        row(q('email', 'Email', { required: true }), q('phone', 'Phone')),
        q('short_text', 'Organisation', { key: 'organisation' }),
      ]),
      page('Speaker', [
        q('short_text', 'Session title', { key: 'session_title' }),
        q('long_text', 'Abstract', { key: 'abstract', validation: { max_length: 1500 } }),
        q('radio', 'Format', { key: 'format', options: opts('Talk (30 min)', 'Workshop (90 min)', 'Panel') }),
        q('url', 'Recording of a past talk', { key: 'past_talk' }),
      ]),
      page('Sponsor', [
        q('radio', 'Package', { key: 'package', options: scored(['Bronze — 2,000', 2000], ['Silver — 5,000', 5000], ['Gold — 10,000', 10000]) }),
        q('checkbox', 'Add-ons', { key: 'addons', options: scored(['Exhibition booth — 1,500', 1500], ['Logo on badges — 800', 800], ['Speaking slot — 2,500', 2500]) }),
        q('calculated', 'Sponsorship total', { key: 'sponsorship_total', formula: '{package} + if(count({addons}) > 0, {addons}, 0)' }),
        q('file_upload', 'Logo (SVG or PNG)', { props: { accept: '.svg,.png', max_files: 1, max_mb: 5 } }),
      ]),
    ],
    logic: [
      rule([['role', 'eq', 'speaker']], [['hide_page', 'Sponsor'], ['require', 'session_title'], ['require', 'abstract']]),
      rule([['role', 'eq', 'sponsor']], [['hide_page', 'Speaker'], ['require', 'organisation'], ['require', 'package']]),
    ],
  },
  {
    key: 'post_event_feedback',
    category: 'events',
    icon: 'i-lucide-party-popper',
    minutes: 3,
    name: 'Post-Event Feedback',
    description: 'Ratings for content, speakers, venue and organisation with an average score and a recommendation.',
    tags: ['feedback', 'event'],
    pages: [
      page('Your feedback', [
        q('short_text', 'Event', { required: true }),
        q('rating', 'Overall', { key: 'r_overall', required: true }),
        row(q('rating', 'Content', { key: 'r_content' }), q('rating', 'Speakers', { key: 'r_speakers' })),
        row(q('rating', 'Venue', { key: 'r_venue' }), q('rating', 'Organisation', { key: 'r_organisation' })),
        q('calculated', 'Average rating', { key: 'average', formula: 'round(avg({r_overall}, {r_content}, {r_speakers}, {r_venue}, {r_organisation}), 1)' }),
        q('scale', 'How likely are you to recommend this event?', { props: { min: 0, max: 10, min_label: 'Not likely', max_label: 'Very likely' } }),
        q('checkbox', 'Best parts', { options: opts('Talks', 'Workshops', 'Networking', 'Venue', 'Food') }),
        q('long_text', 'What should we improve?'),
        q('radio', 'Would you come again?', { options: opts('Yes', 'Maybe', 'No') }),
      ]),
    ],
  },
]
