/** Hospitality templates (F9 milestone 2). */
import { opts, page, q, row, rule, scored, type TemplateDef } from '../kit'

const fiveStars = scored(['Very poor', 1], ['Poor', 2], ['Fair', 3], ['Good', 4], ['Excellent', 5])

export const HOSPITALITY_TEMPLATES: TemplateDef[] = [
  {
    key: 'guest_registration',
    category: 'hospitality',
    icon: 'i-lucide-hotel',
    minutes: 4,
    name: 'Guest Registration Form',
    description: 'Check-in details with the number of nights worked out from arrival and departure.',
    tags: ['check-in', 'guest', 'hotel'],
    pages: [
      page('Guest registration', [
        q('full_name', 'Full name', { required: true }),
        row(q('email', 'Email', { required: true }), q('phone', 'Phone', { required: true })),
        row(q('country', 'Nationality'), q('short_text', 'Passport or ID number')),
        q('address', 'Home address'),
        row(q('date', 'Arrival', { key: 'arrival', required: true }), q('date', 'Departure', { key: 'departure', required: true })),
        row(
          q('calculated', 'Nights', { key: 'nights', formula: 'days({arrival}, {departure})' }),
          q('number', 'Number of guests', { required: true, default: 1, validation: { min: 1, max: 12 } }),
        ),
        q('short_text', 'Vehicle registration (if parking)'),
        q('consent', 'House rules', { required: true, props: { text: 'I have read and accept the house rules.' } }),
        q('signature', 'Signature', { required: true }),
      ]),
    ],
  },
  {
    key: 'hotel_booking_request',
    category: 'hospitality',
    icon: 'i-lucide-bed-double',
    minutes: 3,
    name: 'Hotel Booking Request Form',
    description: 'Dates, room type and rooms give the nights and an estimated price; extras and special requests too.',
    tags: ['booking', 'hotel', 'rooms'],
    pages: [
      page('Booking request', [
        q('full_name', 'Name', { required: true }),
        row(q('email', 'Email', { required: true }), q('phone', 'Phone')),
        row(q('date', 'Check-in', { key: 'check_in', required: true }), q('date', 'Check-out', { key: 'check_out', required: true })),
        q('dropdown', 'Room type', { key: 'room_type', required: true, options: scored(['Standard — 120.00 / night', 120], ['Deluxe — 180.00 / night', 180], ['Suite — 320.00 / night', 320]) }),
        row(
          q('number', 'Rooms', { key: 'rooms', required: true, default: 1, validation: { min: 1, max: 10 } }),
          q('number', 'Adults', { required: true, default: 2, validation: { min: 1, max: 20 } }),
          q('number', 'Children', { default: 0, validation: { min: 0, max: 20 } }),
        ),
        row(
          q('calculated', 'Nights', { key: 'nights', formula: 'days({check_in}, {check_out})' }),
          q('calculated', 'Estimated price', { key: 'estimate', formula: '{nights} * {room_type} * {rooms}', help: 'Before taxes and extras; the hotel confirms the final price.' }),
        ),
        q('checkbox', 'Extras', { options: opts('Breakfast', 'Airport transfer', 'Late check-out', 'Parking') }),
        q('long_text', 'Special requests'),
      ]),
    ],
  },
  {
    key: 'guest_feedback',
    category: 'hospitality',
    icon: 'i-lucide-message-circle-heart',
    minutes: 3,
    name: 'Guest Feedback Form',
    description: 'Rate cleanliness, comfort, staff, food and value with an average and a recommendation.',
    tags: ['feedback', 'stay', 'guest'],
    pages: [
      page('Your stay', [
        row(q('date', 'Date of stay'), q('short_text', 'Room number')),
        row(q('rating', 'Cleanliness', { key: 'r_clean', required: true }), q('rating', 'Comfort', { key: 'r_comfort', required: true })),
        row(q('rating', 'Staff', { key: 'r_staff', required: true }), q('rating', 'Food and drink', { key: 'r_food' })),
        q('rating', 'Value for money', { key: 'r_value' }),
        q('calculated', 'Average rating', { key: 'average', formula: 'round(avg({r_clean}, {r_comfort}, {r_staff}, {r_food}, {r_value}), 1)' }),
        q('scale', 'How likely are you to recommend us?', { props: { min: 0, max: 10, min_label: 'Not likely', max_label: 'Very likely' } }),
        q('long_text', 'What did you enjoy most?'),
        q('long_text', 'What could we improve?'),
        q('toggle', 'You may contact me about my feedback', { key: 'may_contact' }),
        q('email', 'Email', { key: 'contact_email' }),
      ]),
    ],
    logic: [rule([['may_contact', 'true']], [['show', 'contact_email'], ['require', 'contact_email']])],
  },
  {
    key: 'service_evaluation',
    category: 'hospitality',
    icon: 'i-lucide-concierge-bell',
    minutes: 2,
    name: 'Service Evaluation Form',
    description: 'Evaluate a department or team member on four qualities; the service score is shown as a percentage.',
    tags: ['service', 'evaluation', 'staff'],
    pages: [
      page('Service evaluation', [
        row(
          q('dropdown', 'Department', { required: true, options: opts('Front desk', 'Housekeeping', 'Restaurant', 'Spa', 'Concierge', 'Room service') }),
          q('short_text', 'Team member (optional)'),
        ),
        q('date', 'Date of service'),
        ...['Friendliness', 'Speed', 'Knowledge', 'Solving problems'].map((label, i) => q('radio', label, { key: `q${i + 1}`, required: true, options: fiveStars })),
        q('calculated', 'Service score (%)', { key: 'service_score', formula: 'round((avg({q1}, {q2}, {q3}, {q4}) - 1) / 4 * 100)' }),
        q('long_text', 'Comments'),
      ]),
    ],
  },
  {
    key: 'special_requirements',
    category: 'hospitality',
    icon: 'i-lucide-heart-handshake',
    minutes: 3,
    name: 'Special Requirements Form',
    description: 'Dietary and access needs, allergies and celebrations — so the stay is ready before arrival.',
    tags: ['dietary', 'accessibility', 'allergies'],
    pages: [
      page('Special requirements', [
        row(q('full_name', 'Guest name', { required: true }), q('short_text', 'Booking reference', { required: true })),
        q('date_range', 'Stay dates'),
        q('checkbox', 'Dietary needs', { options: opts('Vegetarian', 'Vegan', 'Halal', 'Kosher', 'Gluten-free', 'Lactose-free') }),
        q('toggle', 'Do you have food allergies?', { key: 'allergies' }),
        q('long_text', 'Allergies and how severe they are', { key: 'allergy_details' }),
        q('checkbox', 'Access needs', { options: opts('Step-free access', 'Accessible bathroom', 'Ground floor', 'Hearing loop', 'Space for a mobility aid') }),
        q('radio', 'Are you celebrating?', { key: 'celebration', options: opts('Birthday', 'Anniversary', 'Honeymoon', 'Other', 'No') }),
        q('short_text', 'Tell us about the occasion', { key: 'celebration_details' }),
        q('long_text', 'Anything else'),
      ]),
    ],
    logic: [
      rule([['allergies', 'true']], [['show', 'allergy_details'], ['require', 'allergy_details']]),
      rule([['celebration', 'in', ['birthday', 'anniversary', 'honeymoon', 'other']]], [['show', 'celebration_details']]),
    ],
  },
  {
    key: 'event_catering_request',
    category: 'hospitality',
    icon: 'i-lucide-utensils',
    minutes: 4,
    name: 'Event Catering Request',
    description: 'Menu and extras per head times the number of guests give an estimate straight away.',
    tags: ['catering', 'event', 'menu'],
    pages: [
      page('Your event', [
        q('full_name', 'Contact name', { required: true }),
        row(q('email', 'Email', { required: true }), q('phone', 'Phone', { required: true })),
        row(q('date', 'Event date', { required: true }), q('time', 'Serving time')),
        q('address', 'Event location'),
        q('number', 'Number of guests', { key: 'guests', required: true, validation: { min: 5, max: 2000 } }),
      ]),
      page('Menu', [
        q('radio', 'Menu (per guest)', { key: 'menu', required: true, options: scored(['Canapés — 18.00', 18], ['Buffet — 25.00', 25], ['Three-course meal — 45.00', 45]) }),
        q('checkbox', 'Extras (per guest)', { key: 'extras', options: scored(['Drinks package — 15.00', 15], ['Dessert table — 6.00', 6], ['Coffee and tea — 3.00', 3]) }),
        row(
          q('calculated', 'Price per guest', { key: 'per_guest', formula: '{menu} + if(count({extras}) > 0, {extras}, 0)' }),
          q('calculated', 'Estimated total', { key: 'estimate', formula: '{per_guest} * {guests}' }),
        ),
        q('long_text', 'Dietary needs (numbers of guests)'),
        q('long_text', 'Other wishes'),
      ]),
    ],
  },
  {
    key: 'restaurant_reservation',
    category: 'hospitality',
    icon: 'i-lucide-utensils-crossed',
    minutes: 2,
    name: 'Restaurant Reservation Request',
    description: 'Date, time, party size, seating and the occasion — everything the host needs.',
    tags: ['restaurant', 'reservation', 'table'],
    pages: [
      page('Reserve a table', [
        q('full_name', 'Name', { required: true }),
        row(q('phone', 'Phone', { required: true }), q('email', 'Email')),
        row(q('date', 'Date', { required: true }), q('time', 'Time', { required: true }), q('number', 'Guests', { required: true, default: 2, validation: { min: 1, max: 30 } })),
        q('radio', 'Seating', { options: opts('Indoors', 'Outdoors', 'Bar', 'No preference') }),
        q('dropdown', 'Occasion', { options: opts('None', 'Birthday', 'Anniversary', 'Business', 'Other') }),
        q('toggle', 'We need a high chair'),
        q('long_text', 'Special requests or allergies'),
      ]),
    ],
  },
  {
    key: 'hospitality_complaint',
    category: 'hospitality',
    icon: 'i-lucide-message-square-warning',
    minutes: 4,
    name: 'Hospitality Complaint Form',
    description: 'Let guests tell you what went wrong, where and how they would like it put right.',
    tags: ['complaint', 'guest'],
    pages: [
      page('Your complaint', [
        q('full_name', 'Name', { required: true }),
        row(q('email', 'Email', { required: true }), q('short_text', 'Booking reference')),
        row(
          q('date', 'Date', { required: true }),
          q('dropdown', 'Area', { required: true, options: opts('Room', 'Restaurant', 'Front desk', 'Housekeeping', 'Facilities', 'Billing', 'Other') }),
        ),
        q('radio', 'How serious is this for you?', { options: opts('Minor', 'Significant', 'Serious') }),
        q('long_text', 'What happened?', { required: true, validation: { min_length: 20 } }),
        q('long_text', 'How would you like us to put it right?'),
        q('image_upload', 'Photos', { props: { max_files: 4 } }),
        q('toggle', 'Did you already speak to a member of staff?', { key: 'spoke' }),
        q('short_text', 'Who did you speak to, and when?', { key: 'spoke_details' }),
      ]),
    ],
    logic: [rule([['spoke', 'true']], [['show', 'spoke_details']])],
  },
]
